name=robot_hand_library
version=1.0.0
author=Seunghyun Baek
maintainer=shbaek03@postech.ac.kr
sentence=Servo control with Adafruit PWM Driver.
paragraph=Wraps Adafruit_PWMServoDriver to simplify angle-based control with Serial parsing.
category=Signal Input/Output
url=https://github.com/yourname/ServoController
architectures=*
depends=Adafruit_PWMServoDriver